backup.gemspec
Ruby 2.2.0 does not build gem json 1.8.1.
It was fixed in 1.8.2 version.
Need to update backup dependency, to make it possible to use with ruby 2.2.0
=> Update json dependency

templates/cli/databases/sqlite
Commit b0f6dc5 removed the :name accessor. This fixes the CLI template to reflect this.
=> Fix SQLite CLI template

lib/backup/config/dsl.rb
The config DSL notifiers did not have data dog listed so even though there was a notifier for it the DataDog notification could not be used.  So I fixed it.
=> fix data dog notifier

Gemfile.lock, backup.gemspec
Fog 1.27.0 had a duplicate key in a hash (https://github.com/fog/fog/commit/b8981c1d90d2954aca29fbebd30c789cfb83f08e) which created a warning on Ruby 2.2 every time backup ran.
=> update fog to v1.28.0

lib/backup/encryptor/open_ssl.rb, spec/encryptor/open_ssl_spec.rb
This ensures that the single quote character `'` can be used in an `Encryptor::OpenSSL` password.
Fixes this bug:
```
[2015/04/08 17:17:55][info] Using Encryptor::OpenSSL to encrypt the archive.
[2015/04/08 17:17:55][warn]   Pipeline STDERR Messages:
[2015/04/08 17:17:55][warn]   (Note: may be interleaved if multiple commands returned error messages)
[2015/04/08 17:17:55][warn] 
[2015/04/08 17:17:55][warn]   sh: 1: Syntax error: Unterminated quoted string
```
=> Properly escape passwords when passing to openssl

lib/backup.rb, lib/backup/config/dsl.rb, lib/backup/notifier/command.rb, spec/cli_spec.rb, spec/notifier/command_notifier_spec.rb, templates/cli/notifiers/command
I added a notifier that just invokes a command. Useful for example for Ubuntu's OSD notifications (notify-send).
Do you need documentation apart from the rdoc?
=> Command notifier

lib/backup/model.rb, spec/model_spec.rb
So that when one storage does not work, data has a chance of being stored elsewhere.
I had a recent experience, where backups configured to be stored via SCP and S3 storages were failing due to connection issues to SCP destination. Connection to S3 was still usable, but no backups were being made via that because SCP was attempted first, and failing.
=> Attempt all configured Storages, regardless of errors

lib/backup/notifier/base.rb, lib/backup/notifier/campfire.rb, lib/backup/notifier/datadog.rb, lib/backup/notifier/flowdock.rb, lib/backup/notifier/hipchat.rb, lib/backup/notifier/http_post.rb, lib/backup/notifier/mail.rb, lib/backup/notifier/nagios.rb, lib/backup/notifier/prowl.rb, lib/backup/notifier/pushover.rb, lib/backup/notifier/ses.rb, lib/backup/notifier/slack.rb, lib/backup/notifier/twitter.rb, lib/backup/notifier/zabbix.rb, spec/notifier/datadog_spec.rb, spec/notifier/flowdock_spec.rb, spec/notifier/nagios_spec.rb, spec/notifier/prowl_spec.rb, spec/notifier/twitter_spec.rb, spec/notifier/zabbix_spec.rb
This change makes it possible to customize messages send through notifiers. Closes #697
The following notifiers have been updated to use the `message` lambda to compose message. Their messages also use the standard format of:
```
[Backup::Success] test model (test_trigger)
[Backup::Warning] test model (test_trigger)
[Backup::Failure] test model (test_trigger)
```
- Campfire
- Datadog (with `text` attribute deprecation)
- Flowdock
- HipChat
- Http post
- Mail
- Nagios
- Prowl (uses message: `test model (test trigger)`, because the event title is the `Backup::Success` label)
- Pushover
- SES
- Slack
- Twitter
- Zabbix
The following notifiers have not been changed to use this method, because they differ too much to use this.
- Command
- Pagerduty
To change the notifier message on the …
=> Allow custom messages in certain notifiers

CHANGELOG.md
I think most (ruby) devs will be looking to a `CHANGELOG` or `HISTORY` file when they want to find out about releases.  This should make sure that they will find what they are looking for.
fixes issue #309
=> link to the release notes

lib/backup/notifier/hipchat.rb, spec/notifier/hipchat_spec.rb
This change allows the hipchat version to be specified, so the hipchat v2 api can be used.
=> Allow hipchat version to be specified.

lib/backup/storage/cycler.rb, spec/support/shared_examples/storage.rb
Currently the cycler fails if the keep value is set. 
I've written a couple of tests which fail with the version 4.2.1 and the simple fix which should fix it.
=> Fix to negative array size error in cycler

lib/backup/syncer/rsync/base.rb, spec/syncer/rsync/local_spec.rb
Apperently the included file permission options in the
`--archive` flag dont work on fuse file systems.
This commit makes it possible to remove the `--archive`
option.
http://blog.marcelotmelo.com/linux/ubuntu/rsync-to-an-exfat-partition/
=> Add support to disable archive option for rsync syncer

lib/backup.rb, spec/package_spec.rb
In normal envs the Time library isn't loaded unless explicitly called.
It works in the test environment, because the timecop gem is loaded and
this requires the time library for us.
Now explictly requiring time and adding a spec for the method that
depends on it (since I forgot to write it when adding it).
Closes #727
=> Require time library

lib/backup/database/mongodb.rb, spec/database/mongodb_spec.rb
While testing the database backup for mongodb we encountered an error.  Authentication failed when trying to use the mongo shell.  Here is a copy of the error:
[2016/02/04 00:49:24][error]   MongoDB shell version: 3.0.1
[2016/02/04 00:49:24][error]   connecting to: localhost:27018/test
[2016/02/04 00:49:24][error]   2016-02-04T00:49:24.750+0000 E QUERY    Error: 18 Authentication failed.
[2016/02/04 00:49:24][error]   at DB._authOrThrow (src/mongo/shell/db.js:1236:32)
[2016/02/04 00:49:24][error]   at (auth):6:8
[2016/02/04 00:49:24][error]   at (auth):7:2 at src/mongo/shell/db.js:1236
[2016/02/04 00:49:24][error]   STDERR Messages: 
[2016/02/04 00:49:24][error]   exception: login failed
When authenticating a user against mongo an option that can be passed is authenticationDatabase. …
=> adding authdb option to the credentials for mongodb

Gemfile, Gemfile.lock, backup.gemspec, lib/backup/storage/dropbox.rb
caused by #762.
Closes #762 
tests pass, needs some more testing in the wild.
=> use dropbox-sdk in newest 1.6.5 version

lib/backup/notifier/mail.rb
Hi
Like [actionmailer](https://github.com/rails/rails/blob/v4.2.6/actionmailer/lib/action_mailer/delivery_methods.rb#L67), maybe ```mail.delivery_method :smtp, options``` is better than ```Mail.defaults{ delivery_method :smtp, options }```
So, please review it. thanks.
=> Remove Mail.defaults

Gemfile.lock, backup.gemspec
We encountered several deprecation warnings when running the backups
```
/usr/local/rvm/gems/ruby-2.3.1@global/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/local/rvm/gems/ruby-2.3.1@global/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/local/rvm/gems/ruby-2.3.1@global/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/local/rvm/gems/ruby-2.3.1@global/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
```
I upgraded net-ssh and regenerated the …
=> upgrade net-ssh

lib/backup/database/postgresql.rb, spec/database/postgresql_spec.rb
As mentioned already in #695 , this is a common issue with postgresql backups + use_sudo.
A better fix than ignoring the logs would be to use sudo -H
=> Fix [warn] could not change directory to "/root"

lib/backup/notifier/ses.rb, spec/notifier/ses_spec.rb
Similiar to existing functionality in the Mail notifier, allow the SES notifier
to set CC, BCC, and Reply-To headers in the e-mails it sends (via SES).
=> Add support for setting CC, BCC, and Reply-To headers in SES notification e-mails

lib/backup/notifier/mail.rb, spec/notifier/mail_spec.rb
Hi
I want to use SES (with IAM user) to send mail notifier.
One solution is [Notifier::Ses](http://backup.github.io/backup/v4/notifier-ses/), in this [issue](https://github.com/drewblas/aws-ses/issues/31), I found aws-ses gem should use [AWS Access Keys](https://console.aws.amazon.com/iam/home#security_credential), but AWS Access Keys was not recommend.
Another solution is [Notifier::Mail](http://backup.github.io/backup/v4/notifier-mail/), I try to run it with following scripts, the ```lib/ruby/2.2.0/net/smtp.rb:964:in `check_response': 501 Syntax: HELO <hostname> (Net::SMTPSyntaxError)``` error happened
```ruby
require "backup"
model = Backup::Model.new :trigger, 'label'
notifier = Backup::Notifier::Mail.new model
notifier.delivery_method = :smtp
notifier.address = …
```
=> Mail notifier support smtp with Amazon SES (with IAM user)

lib/backup/notifier/command.rb
I would like to use the backup duration in a custom command line notifier. This patch should provide it as an argument, %d.
=> Add duration to the command line notifier

.rspec, Gemfile, Gemfile.lock
It's a development preference.
=> Remove fuubar rspec progress bar

CONTRIBUTING.md
This adds a new CONTRIBUTING.md file, per #806. I've kept it as concise as possible, since it gets shown to both bug reporters and potential contributors: it occurred to me that we could have a separate file to have more details on the development process without overloading people who just want to report an issue.
I've deliberately not included items that are being discussed on other tickets, or might need more work:
* Whether there should be a separate Security section, and if so, what contact information to give
* Coding style
* The testing process
=> Add CONTRIBUTING.md, GH #806

backup.gemspec
CVE-2016-4658 and CVE-2016-5131 [were fixed in nokogiri 1.7.1](https://github.com/sparklemotion/nokogiri/issues/1615).
Loosen dependency for:
- thor
- json
- nokogiri
- twitter (http gem CVE-2015-1828)
- qiniu (rest-client CVE-2015-1820)
=> Bump nokogiri to 1.7.1

lib/backup/cli.rb, spec/cli_spec.rb
Thor upgrade that checks for option types outputted the following:
```
Expected string default value for '--quiet'; got false (boolean)
Expected string default value for '--syslog'; got false (boolean)
Expected string default value for '--logfile'; got true (boolean)
```
Changed these option types to boolean from string, as the default value
was a boolean and the warnings disappear.
=> Fix CLI option types 

backup.gemspec, lib/backup/notifier/mail.rb, lib/backup/notifier/ses.rb, spec/notifier/ses_spec.rb
Sadly, the `aws-ses` gem doesn't support IAM instance profiles, so just swap it out for the official `aws-sdk` gem.
Fixes #666.
=> Swap Notifier::Ses to use `aws-sdk` gem and add support for IAM instance profiles

.rubocop_todo.yml, lib/backup/model.rb, lib/backup/utilities.rb
Deprecates Databases, syncers, storage and notifiers as listed in #851.
Example output:
```
[2017/04/23 14:20:59][warn] The Backup database "OpenLDAP" is scheduled to be deprecated. If you're using this feature, please see: https://github.com/backup/backup/issues/851
[2017/04/23 14:20:59][warn] The Backup syncer "Cloud::CloudFiles" is scheduled to be deprecated. If you're using this feature, please see: https://github.com/backup/backup/issues/851
```
Closes #851
=> Deprecate certain Backup features

backup.gemspec, lib/backup/notifier/mail.rb
`mail` v2.6.6 -- https://github.com/mikel/mail/releases/tag/2.6.6
`nokogiri` v1.7.2 -- https://github.com/sparklemotion/nokogiri/blob/v1.7.2/CHANGELOG.md#172--2017-05-09
The `mail` patch for Exim SMTP support is [no longer required](https://github.com/mikel/mail/commit/67ac9bb7128c3e3f74ee4f8e7115a00727652876) as well.
=> Bump `mail` and `nokogiri` dependencies for security updates

.dockerignore, Dockerfile, Rakefile, docker-compose.yml, integration/acceptance/archive_spec.rb, integration/spec_helper.rb, integration/support/example_helpers.rb, integration/support/logger.rb, integration/support/match_manifest.rb, integration/support/package.rb, integration/support/performed_job.rb, integration/support/tarfile.rb, integration/tasks/files.rake, integration/tasks/fileset_builder.rb
This PR adds Docker support for testing. It supersedes PR #832.
The first commit adds Docker, and a Rake task for running the RSpec unit tests inside the container.
The second commit enables integration tests to run inside the container, adds the supporting code for testing generated backup archives, and provides one integration test (in integration/acceptance/archive_spec.rb).
=> Docker for testing (second version)

.dockerignore, Dockerfile, Rakefile, bin/docker_test, docker-compose.yml
@stuartellis Great work on #857 ! Sorry I wasn't more active to review it.
I had a look and wondered why the image includes the bundle as that could introduce a stale state between the bundle on the image and the bundle of the project. Especially since it doesn't automatically build the image before running a command on a docker container.
To fix that I applied some of the setup I've recently setup for some other Docker testing projects.
Let me know if this sounds like a good idea to apply here too
Also wasn't sure why the `-I` and `-S` options were used for the Ruby scripts on the docker containers. Seems to work without it? If I missed some application of this, it might be nicer to move this setup to some of the files, so they're not reliant of the command that runs the test suites.
--- …
=> Don't store project files on docker image

v4/storage-s3/index.md
As mentioned in #898, this PR adds a bit to the docs covering usage with S3-compatible APIs like DigitalOcean's Spaces.
=> Document usage with S3-compatible APIs like DigitalOcean's Spaces.

Dockerfile
This PR raises the version of Ruby for Docker to 2.4.3. The spec and integration tests work without change.
=> Raise Ruby version for tests to 2.4.3

.travis.yml
support for 2.2 and 2.1 has ended 
https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/ and 
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
=> Update .travis.yml : support for 2.2 and 2.1 has ended 

lib/backup/storage/ftp.rb
The default passive setting has been changed between Ruby 2.2 and 2.3
=> Ensure the default FTP passive settings to false

CONTRIBUTING.md, TC.md
This PR refers to on-going discussion in #803 
Those changes are largely based on the node.js community base policies: https://raw.githubusercontent.com/nodejs/TSC/master/BasePolicies/CONTRIBUTING.md
=> Document suggested community-based governance model

v4/storage-s3/index.md
Adds additional documentation to use S3-compatible services like Minio.
Specifically, it describes the required _fog-options_ to connect this Gem with Minio running in Docker.
See this issue: https://github.com/backup/backup/issues/962
=> Add Minio specific storage configuration

lib/backup/encryptor/open_ssl.rb, spec/encryptor/open_ssl_spec.rb
Use public key derivation function 2 with OWASP recommended iterations  (cf #949)
Also deprecate the `salt` attribute with is the default anyway (see `man enc`)
=> Openssl pbkdf2

.github/workflows/rspec.yml, backup.gemspec, lib/backup/template.rb, spec/support/sandbox_file_utils.rb, spec/support/shared_examples/storage.rb
This PR is a first pass at working on ruby 3.1 compat for backup.
* BREAKING CHANGE*: Support is dropped for rubies < 2.3 (TBH, I'm considering dropping support for ruby < 2.5, which is current debian oldstable)
* Various minor fixes
=> Ruby 3.1 compatibility

backup.gemspec
[A couple months ago](https://github.com/backup/backup/commit/49bf0fd47b7955f3e1d9cd83014c57389aeab37c) `net-smtp ~>1.0.1` was added as an explicit dependency to this gem.
However, this version still uses the `$SAFE` global variable that was since then removed from Ruby 3.0 (https://bugs.ruby-lang.org/issues/16131), so when I sent a notification email after a backup, I got this error: 
```
NoMethodError: undefined method `>' for nil:NilClass
if $SAFE > 0
^^^^^^^^^^
```
Relaxing the dependency fixed this issue because the code using `$SAFE` was removed from `net-smtp 0.2.0`: https://github.com/ruby/net-smtp/commit/8fbd08af6cebbb111d2172090531fa60fa6275f3
=> Relax "net-smtp" dependency (to fix `$SAFE > 0`)
